# PR Gate: Lint and test on PRs to main branches
name: PR Gate

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main

jobs:
  pr-gate:
    name: PR Gate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        run: pip install uv
      - name: Sync dependencies
        run: uv sync --all-extras --dev
      - name: Lint
        run: uv run ruff check
      - name: Test
        run: uv run pytest
